name: etraveler
channels:
  - defaults
dependencies:
  - Babel==2.8.0
  - backcall==0.2.0
  - certifi==2020.6.20
  - cffi==1.14.4
  - chardet==3.0.4
  - click==7.1.2
  - colorama==0.4.4
  - cryptography==3.2.1
  - cycler==0.10.0
  - decorator==4.4.2
  - Flask==1.1.2
  - Flask-WTF==0.14.3
  - future==0.18.2
  - idna==2.10
  - ipython==7.19.0
  - iso8601==0.1.13
  - itsdangerous==1.1.0
  - jdcal==1.4.1
  - jedi==0.17.2
  - Jinja2==2.11.2
  - kiwisolver==1.3.1
  - MarkupSafe==1.1.1
  - matplotlib==3.3.2
  - mpld3==0.5.1
  - numpy==1.19.2
  - openpyxl==3.0.6
  - pandas==1.1.2
  - pickleshare==0.7.5
  - Pillow==8.0.1
  - pip=21.1.1
  - plotly==4.14.3
  - prompt-toolkit==3.0.8
  - protobuf==3.13.0
  - pycparser==2.20
  - Pygments==2.7.2
  - PyMySQL==0.10.1
  - pyparsing==2.4.7
  - pyserial==3.4
  - python-dateutil==2.8.1
  - pytz==2020.1
  - PyYAML==5.3.1
  - requests==2.24.0
  - retrying==1.3.3
  - six==1.15.0
  - SQLAlchemy==1.3.19
  - traitlets==5.0.5
  - urllib3==1.25.10
  - wcwidth==0.2.5
  - websocket-client==0.57.0
  - Werkzeug==1.0.1
  - WTForms==2.3.3
  - xlrd==1.2.0
  - pip:
    - alpaca-trade-api==0.50.1
    - chart-studio==1.1.0
    - et-xmlfile==1.0.1
    - flask-mysql-connector==1.0.3
    - ipython-genutils==0.2.0
    - mysql-connector-python==8.0.21
    - parso==0.7.1
    - pydrive==1.3.1
    - serial==0.0.97
    - tkcalendar==1.6.1
    - websockets==8.1